apiVersion: apps/v1
kind: Deployment
metadata:
  name: rco-controller-manager
  namespace: runtime-component
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: WATCH_NAMESPACE
              value: ""
              valueFrom:
