apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: runtime-component


resources:
- ../../base

configMapGenerator:
  - envs:
      - operator.properties
    name: app-config

replacements:
- source:
    kind: ConfigMap
    name: app-config
    fieldPath: data.MAX_CONCURRENT_RECONCILES
  targets:
  - select:
      name: rco-controller-manager
      kind: Deployment
    fieldPaths:
      - spec.template.spec.containers.[name=manager].env.[name=MAX_CONCURRENT_RECONCILES].value