type: pipeline_definition
product: Liberty
name: Runtime Componet Operator Docker Build
description: A build to run the runtime-component operator docker container build
triggers:
- type: manual
  triggerName: "rcodocker"
  propertyDefinitions:
  - name: RELEASE_TARGET
    defaultValue: "main"        
  - name: command
    defaultValue: "make build-operator-pipeline REGISTRY=cp.stg.icr.io"

steps:
- stepName: Z Build
  workType: Jenkins
  projectName: ebcDockerBuilderRCO
  timeoutInMinutes: 1440
  # Need properties for Makefile or build script for RCO
  properties:  
    ebcPlan: svl-dockerJenkins-ubuntu22_z_fyrev3.yml
    

- stepName: P Build
  workType: Jenkins
  projectName: ebcDockerBuilderRCO
  timeoutInMinutes: 1440
  # Need properties for Makefile or build script for RCO
  properties:  
    ebcPlan: svl-dockerJenkins-ubuntu22_p9_fyrev3.yml

- stepName: ARM Build
  workType: Jenkins
  projectName: ebcDockerBuilderRCO
  timeoutInMinutes: 1440
  # Need properties for Makefile or build script for WLO
  properties:  
    ebcPlan: managed-pool-jenkins-macosx_arm.yml
