apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rco-ns


resources:
- ../../overlays/watch-all-namespaces
patches:
- path: rco-leader-election-cluster-rolebinding.yaml
- path: rco-manager-cluster-rolebinding.yaml
