FROM ubuntu:22.04

ARG GO_VERSION

env PATH=$PATH:/usr/local/go/bin

WORKDIR /workspace

RUN apt update -y && apt install -y curl sudo gpg make build-essential wget

RUN wget --no-verbose --header "Accept: application/octet-stream" "https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz" -O - | tar -xz -C /usr/local/

COPY . .

RUN operators/scripts/installers/install-operator-sdk.sh

CMD [ "bash" ]
