apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: runtime-component-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: runtime-component-operator
  name: rco-controller-manager
