apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rco-ns


resources:
- ../../../base
patches:
- path: rco-deployment.yaml
- path: rco-leader-election-role.yaml
- path: rco-manager-role.yaml
- path: rco-leader-election-rolebinding.yaml
- path: rco-manager-rolebinding.yaml
- path: rco-sa.yaml
