apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rco-ns


resources:
- ../../../base
patches:
- path: rco-deployment.yaml
- path: roles1.yaml
- path: roles2.yaml
- path: roles3.yaml
- path: roles4.yaml
- path: rco-sa.yaml
