apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rco-manager-rolebinding
  namespace: runtime-component
subjects:
- kind: ServiceAccount
  name: rco-controller-manager
  namespace: runtime-component
