= Installing the Runtime Component Operator using kustomize

This directory contains configuration files that helps installing the Runtime Component operator
using `kustomize` with the Kubernetes command-line interface (CLI) (`kubectl`). These configurations
are useful when the cluster is not a Red Hat® OpenShift® Container Platform cluster or when
Operator Lifecycle Manager is not being used.

== Installing and watching own namespace

=== base
The base configuration installs the operator into the 'runtime-component' namespace,
and the operator watches for Runtime Component custom resource instances only in its own namespace.
Create a namespace called 'runtime-component' for the operator.
To install, run: `kubectl create -k base` and to uninstall, run: `kubectl delete -k base`

=== examples/watch-own-namespace
This example overlay demonstrates how to modify the base configuration to install the operator and have it
watch a namespace other than 'runtime-component'. Create a namespace called 'rco-ns' for the operator.
To install the operator into the 'rco-ns' namespace, run: `kubectl create -k examples/watch-own-namespace`

== Installing and watching another namespace

=== overlays/watch-another-namespace
This overlay installs the operator into the namespace 'rco-ns', but configures it to
watch for Runtime Component custom resource instances in a different namespace called 'rco-watched-ns'.
Because this overlay installs resources into two different namespaces, the namespace must not be specified
in the kustomize.yaml file. To install, run:  `kubectl create -k overlays/watch-another-namespace`

=== examples/watch-another-namespace
This example overlay builds on the previous example, but demonstrates how to change
the install and watched namespaces. In this case, the operator is installed into 'rco-ns2'
and watches for resources in 'rco-watched-ns2'. To install run: `kubectl create -k
examples/watch-another-namespace`

== Installing and watching all namespaces

=== overlays/watch-all-namespaces
This overlay installs the operator into the 'runtime-component' namespace,
but configures it to watch for Runtime Component custom resource instances in any namespaces.
Compared to the base configuration, this overlay requires additional ClusterRoles and ClusterRoleBindings.
To install, run: `kubectl create -k overlays/watch-all-namespaces`

=== examples/watch-all-namespaces
This example overlay builds on the previous example and demonstrates how to change
the namespace that the operator installs into. In this example, the operator installs
into a namespace that is called 'rco-ns' and watches for Runtime Component custom resource
instances in any namespaces. To install, run: `kubectl create -k examples/watch-all-namespaces`

== Setting max concurrent reconciles

=== overlays/set-max-concurrent-reconciles
This overlay updates the base configuration by setting the `MAX_CONCURRENT_RECONCILES` environment variable in the operator's Deployment. It enables multiple workers to reconcile the Runtime Component custom resource instances concurrently. There are `8` workers set by default, and this setting can be customized in the `overlays/set-max-concurrent-reconciles/application.properties` file. To install, run: `kubectl apply -k overlays/set-max-concurrent-reconciles`