apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rco-watched-ns2


resources:
- ../../../overlays/watch-another-namespace/rco-watched-ns
patches:
- path: role1.yaml
- path: role2.yaml
- path: role3.yaml
- path: role4.yaml
