apiVersion: apps/v1
kind: Deployment
metadata:
  name: rco-controller-manager
  namespace: rco-ns
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: WATCH_NAMESPACE
              value: rco-watched-ns
              valueFrom:
