= Troubleshooting

Here are some basic troubleshooting methods to check if the operator is running fine:

* Run the following and check if the output is similar to the following:

[source,sh]
----
  $ oc get pods -l name=runtime-component-operator

  NAME                                            READY     STATUS    RESTARTS   AGE
  runtime-component-operator-584d6bd86d-fzq2n     1/1       Running   0          33m
----

* Check the operators events:

[source,sh]
----
  $ oc describe pod runtime-component-operator-584d6bd86d-fzq2n
----

* Check the operator logs:

[source,sh]
----
  $ oc logs runtime-component-operator-584d6bd86d-fzq2n
----

If the operator is running fine, check the status of the `RuntimeComponent` Custom Resource (CR) instance:

* Check the CR status:

[source,sh]
----
  $ oc get runtimecomponent my-app -o wide

  NAME                      IMAGE                                             EXPOSED   RECONCILED   REASON    MESSAGE   AGE
  my-app                    quay.io/my-repo/my-app:1.0                        false     True                             1h
----

* Check the CR effective fields:

[source,sh]
----
  $ oc get runtimecomponent my-app -o yaml
----

  Ensure that the effective CR values are what you want.

* Check the `status` section of the CR. If the CR was successfully reconciled, the output should look like the following:

[source,sh]
----
  $ oc get runtimecomponent my-app -o yaml

  apiVersion: app.stacks/v1beta1
  kind: RuntimeComponent
  ...
  status:
    conditions:
    - lastTransitionTime: 2019-08-21T22:20:49Z
      status: "True"
      type: Reconciled
----

* Check the CR events:

[source,sh]
----
  $ oc describe runtimecomponent my-app
----


# Known Issues

Operator versions < 0.5.0 might crash on startup when optional CRDs API group (eg. serving.knative.dev/v1alpha1) is
available, but actual CRD (Knative Service) is not present.

Version 0.5.0 of operator can crash when creating Ingress with `spec.expose` is set to `true` and `spec.route` is not provided or set (nil). 
Possible fixes are to set `spec.route` to `{}` or disable Ingress if not used by setting `spec.expose` to `false`

