apiVersion: rc.app.stacks/v1beta2
kind: RuntimeComponent
metadata:
  name: runtimecomponent-sample
spec:
  # Add fields here
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started@sha256:c069799108639810d59a0747c044272585dea7e324ef0e9f1550048a637a8680
  expose: true
  replicas: 1
  service:
    port: 9080
