apiVersion: rc.app.stacks/v1beta2
kind: RuntimeComponent
metadata:
  name: runtimecomponent-sample
spec:
  # Add fields here
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started@sha256:68a92cee3c162f2144a596778a6dc67b96acc5cfa69df9690c6ea1d45722a852
  expose: true
  replicas: 1
  service:
    port: 9080
