apiVersion: rc.app.stacks/v1
kind: RuntimeComponent
metadata:
  name: runtimecomponent-sample
spec:
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started@sha256:323580e543429bd299f127c8956aaf319a670bce619510d3ebb67282afabb514
  expose: true
  manageTLS: true
  replicas: 1
  service:
    port: 9443
  serviceAccount:
    mountToken: true
