apiVersion: rc.app.stacks/v1beta2
kind: RuntimeComponent
metadata:
  name: runtimecomponent-sample
spec:
  # Add fields here
  applicationImage: icr.io/appcafe/open-liberty/samples/getting-started@sha256:1f21552048e7ce6b96564f60025d4d57388de97cb5dd7c243c5372ef14a77d34
  expose: true
  replicas: 1
  service:
    port: 9080
