apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: runtime-component-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: runtime-component-operator
  name: rco-watched-role
  namespace: RUNTIME_COMPONENT_WATCH_NAMESPACE
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  - statefulsets
  verbs:
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - serviceaccounts
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - '*'
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  - imagestreamtags
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - rc.app.stacks
  resources:
  - runtimecomponents
  - runtimecomponents/finalizers
  - runtimecomponents/status
  verbs:
  - '*'
- apiGroups:
  - rc.app.stacks
  resources:
  - runtimeoperations
  - runtimeoperations/finalizers
  - runtimeoperations/status
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - '*'
- apiGroups:
  - serving.knative.dev
  resources:
  - services
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: runtime-component-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: runtime-component-operator
  name: rco-watched-rolebinding
  namespace: RUNTIME_COMPONENT_WATCH_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rco-watched-role
subjects:
- kind: ServiceAccount
  name: rco-controller-manager
  namespace: RUNTIME_COMPONENT_OPERATOR_NAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: runtime-component-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: runtime-component-operator
  name: rco-leader-election-watched-role
  namespace: RUNTIME_COMPONENT_WATCH_NAMESPACE
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: runtime-component-operator
    app.kubernetes.io/managed-by: olm
    app.kubernetes.io/name: runtime-component-operator
  name: rco-leader-election-watched-rolebinding
  namespace: RUNTIME_COMPONENT_WATCH_NAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rco-leader-election-watched-role
subjects:
- kind: ServiceAccount
  name: rco-controller-manager
  namespace: RUNTIME_COMPONENT_OPERATOR_NAMESPACE
