apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rco-watched-ns2

bases:
- ../../../overlays/watch-another-namespace/rco-watched-ns

patchesStrategicMerge:
- watched-roles.yaml