apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../rbac

namePrefix: rco-cluster-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/instance: runtime-component-operator
  app.kubernetes.io/name: runtime-component-operator

patches:
- path: patches/delete-service-account.yaml
  target:
    kind: ServiceAccount
- target:
    namespace: runtime-component-operator
    name: .*
  patch: |-
    - op: remove
      path: /metadata/namespace
- target:
    kind: Role
    name: .*
  patch: |-
    - op: replace
      path: /kind
      value: ClusterRole
- target:
    kind: RoleBinding
    name: .*
  patch: |-
    - op: replace
      path: /kind
      value: ClusterRoleBinding
- target:
    kind: ClusterRoleBinding
    name: .*
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: rco-controller-manager
    - op: replace
      path: /subjects/0/namespace
      value: RUNTIME_COMPONENT_OPERATOR_NAMESPACE
    - op: replace
      path: /roleRef/kind
      value: ClusterRole
- target:
    kind: ClusterRoleBinding
    name: rco-cluster-leader-election-rolebinding
  patch: |-
    - op: replace
      path: /roleRef/name
      value: rco-cluster-leader-election-role
- target:
    kind: ClusterRoleBinding
    name: rco-cluster-manager-rolebinding
  patch: |-
    - op: replace
      path: /roleRef/name
      value: rco-cluster-manager-role

patchesJson6902:
- target:
    kind: ClusterRole
    name: rco-cluster-manager-role
  patch: |-
    - op: add
      path: /rules/-
      value: {"apiGroups":[""],"resources":["namespaces"],"verbs":["get","list","watch"]}