apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rco-ns2

bases:
- ../../../overlays/watch-another-namespace/rco-ns

patchesStrategicMerge:
- rco-deployment.yaml
- rco-roles.yaml
- rco-sa.yaml
