# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/rc.app.stacks_runtimecomponents.yaml
- bases/rc.app.stacks_runtimeoperations.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_runtimecomponents.yaml
#- patches/webhook_in_runtimeoperations.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_runtimecomponents.yaml
#- patches/cainjection_in_runtimeoperations.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

- path: patches/preserveUnknownFields_runtimecomponents.yaml
- path: patches/preserveUnknownFields_runtimeoperations.yaml
# +kubebuilder:scaffold:preserveunknownfieldspatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
