apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rco-watched-rolebinding
  namespace: rco-watched-ns
subjects:
- kind: ServiceAccount
  name: rco-controller-manager
  namespace: rco-ns2
