apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: runtime-component.v0.0.0
  namespace: placeholder
  annotations:
    containerImage: icr.io/appcafe/runtime-component-operator:daily
    createdAt: 2025-02-26T11:04:07Z