apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../rbac

# Adds namespace to all resources.
namespace: runtime-component
namePrefix: rco-

# Labels to add to all resources and selectors.
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: runtime-component-operator
    app.kubernetes.io/name: runtime-component-operator