apiVersion: v1
kind: ServiceAccount
metadata:
  name: runtime-component-operator
  namespace: test-project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: runtime-component-operator
  namespace: test-project
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: runtime-component-operator
  namespace: test-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime-component-operator
  namespace: test-project
spec:
  template:
    spec:
      containers:
        - name: runtime-component-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
