apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../manager

# Adds namespace to all resources.
namespace: runtime-component
namePrefix: rco-

# Labels to add to all resources and selectors.
commonLabels:
  app.kubernetes.io/instance: runtime-component-operator
  app.kubernetes.io/name: runtime-component-operator

patches:
- path: patches/delete-namespace.yaml
- path: patches/watch-namespace.yaml
